### ISSUE TITLE
Provide environmental factors related to the research

### ISSUE THREAD

**Issue by pe3zx** [pe3zx/huawei-block-list#1]
As requested from many sources, I plan to provide more information on environmental factors related to this research, including:

- Android and EMUI version
- Pre-installed applications
- Configuration on services related to Huawei
- Network configuration
- Usage behavior
- Region of VPN server

Please let me know if anyone needs any information that could help clarify this research.

**Comment by TheGamerWithMore** [comment]
This just shows that Huawei is spying on us, it's sending data to the Chinese government!

**Comment by pe3zx** [comment]
Hi @TheGamerWithMore,

The only information I provide on this repository only proof that there are connections to some Chinese domains. It didn't show what data being sent. Your conclusion doesn't reflect my actual intention for this reseatch.

If you have more finding, please let me know.

**Comment by kaustubh0x77** [comment]
Include a way for noobs to run the entire experiment on their phones. It's not clear for newbies.

**Comment by fishcg** [comment]
你知道的太多了

**Comment by pe3zx** [comment]
Update in da9d8bf
