### ISSUE TITLE
How did you find our your phone was calling those dns in China?

### ISSUE THREAD

**Issue by ThiagoSousa** [pe3zx/huawei-block-list#2]
I'd like to check whether my phone makes similar requests for DNS (or maybe something else) for my phone, which is also a Huawei, but an older version: Mate 9. Which software did you do to check the traffic from your phone? Thank you!

**Comment by SergioSV96** [comment]
I am interested in this as well, I would like to find out similar requests from my OnePlus Phone, as it's believed they send data to some fishy urls too.

Thanks!

**Comment by pe3zx** [comment]
Briefly explained on [Network Configuration](https://github.com/pe3zx/huawei-block-list#network-configuration). Hope this help.
